### ISSUE TITLE
Need Help Please

### ISSUE THREAD

**Issue by akumasente** [hawkins/groupme-at-all#11]
Hello i am at the part of your groupme @all tutorial where i am trying to test the bot. Ive tried starting my heroku app but i cant figure it out, would you be so kind as to provide more detailed instructions for someone just learning?

**Comment by hawkins** [comment]
Are you following my blog post on it? https://hawkins.is/writing-about/groupme-at-all

**Comment by akumasente** [comment]
Yes I am following the blog post. I think I narrowed down the issue to
hubot. I don't think I have hubot running properly.

**Comment by hawkins** [comment]
Hmm, can you tell me how you installed Hubot and how you’re running it?

**Comment by akumasente** [comment]
So i followed your link to the getting started with hubot page. and then i
followed the instructions on that page but i dont think my hubot is
actually doing anything.

**Comment by hawkins** [comment]
Ok, can you post terminal commands and outputs or something? I’d love to help but unfortunately I can’t tell anything from “it’s not doing anything” 🤔

**Comment by akumasente** [comment]
thanks for helping btw your awesome. i screenshotted what i have going with
hubot so far.

**Comment by hawkins** [comment]
Sorry, is there supposed to be an image linked? I don’t see any screenshot

**Comment by akumasente** [comment]
yea i linked one. basically i got to the point of naming the bot and
choosing the adapter. i choose the adapter "groupme".

**Comment by hawkins** [comment]
Try replying via the GitHub web interface, your emails aren’t showing any images.

**Comment by akumasente** [comment]
![hubot help pic](https://user-images.githubusercontent.com/25542370/51078812-4ddd2e80-1670-11e9-8399-9800fa593481.png)

**Comment by hawkins** [comment]
Just now seeing this, sorry!

That screenshot doesn't tel me anything but how you set up hubot, though. There's not even a groupme adapter installed there. Were you able to solve this on your own by now?
