### ISSUE TITLE
Blog post has moved

### ISSUE THREAD

**Issue by osamajvd** [hawkins/groupme-at-all#13]
Any chance you have the information from your blog post backed up anywhere? Was looking to extend the functionality a little bit.

**Comment by hawkins** [comment]
Sorry! Hosting provider 10x’d my hosting cost so I couldn’t afford to host it anymore. But yes, you can at least find the source code for it here: 

https://github.com/hawkins/is/blob/master/pages/writing-about/groupme-at-all.js

**Comment by hawkins** [comment]
Okay, I've re-hosted the blog here: https://dev.to/hawkinjs/using-hubot-to-mention-everyone-in-groupme-3ge

Thanks for calling this to my attention. Hopefully you got it working in the mean time!
